server:
  port: 8082
spring:
  application:
    name: zipkin-demo-server2
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
sample:
  zipkin:
    enabled: true